# docker-compose.yml
version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    environment:
      # désactive l’assistant de démarrage (optionnel)
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_home:/var/jenkins_home
      # accès au daemon Docker de la VM
      - /var/run/docker.sock:/var/run/docker.sock
      # conservez le cache npm/Cypress entre les builds
      - ~/.cache:/var/jenkins_home/.cache

volumes:
  jenkins_home:
