version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17  # ✅ image Jenkins avec Java + Docker possible
    container_name: jenkins
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 🔥 accès au Docker de ta machine pour lancer d'autres containers

  cypress:
    image: cypress/included:12.17.4
    container_name: cypress
    entrypoint: ["tail", "-f", "/dev/null"]

  newman:
    image: postman/newman:latest
    container_name: newman
    entrypoint: ["tail", "-f", "/dev/null"]

  k6:
    image: grafana/k6
    container_name: k6
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  jenkins_home:
